# Generated by Django 3.0.8 on 2020-07-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('E_id', models.IntegerField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=50, verbose_name='源点')),
                ('target', models.CharField(max_length=50, verbose_name='终点')),
                ('value', models.CharField(max_length=50, verbose_name='关系名称')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('N_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('belong_to', models.CharField(max_length=50, verbose_name='结点归类')),
                ('desc', models.CharField(max_length=50, verbose_name='描述')),
                ('category', models.IntegerField(max_length=50, verbose_name='结点类别')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
        ),
    ]
